AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  untitled

  Sample SAM Template for untitled

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        DB_HOST: 'matching-app.c7sscag513cv.ap-northeast-2.rds.amazonaws.com'
        DB_NAME: 'matching_app'
        DB_USER: 'matching_user'
        DB_PASS: 'Matching1234'

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
  testFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.test_json
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /test
            Method: get
  getUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.get_account
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /accounts
            Method: get
  getProfile:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.get_profile
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /profile/{id}
            Method: get
  getProfileList:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.get_profile_list
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /profile
            Method: get
  getProfileImages:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.get_images_all
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /profile/{id}/images
            Method: get
  setGenderInterestedIn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.set_gender_interested_in
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /profile/date/gender
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  getUser:
    Description: "getUser Function ARN"
    Value: !GetAtt getUser.Arn
  getProfile:
    Description: "getProfile Function ARN"
    Value: !GetAtt getProfile.Arn
  getProfileImages:
    Description: "getProfileImages Function ARN"
    Value: !GetAtt getProfileImages.Arn
  setGenderInterestedIn:
    Description: "getGenderInterestedIn Function ARN"
    Value: !GetAtt setGenderInterestedIn.Arn
  testFunction:
    Description: "testFunction Function ARN"
    Value: !GetAtt testFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
